version: "3.8"
services:
  mongodb:
    container_name: mongodb
    image: mongo:4.4
    restart: always
    networks:
      - backend
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes: 
      - mongodb_data_container:/data/db

  backend:
    image: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    build:
      context: ./
      dockerfile: Dockerfile
    command: ["npm", "run","start:dev"]
    restart: on-failure
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes: 
  mongodb_data_container:
